name: 'Create Issue Branch'
description: 'GitHub action that creates a new branch after assigning an issue.'
branding:
  icon: 'activity'
  color: 'blue'
runs:
  using: 'node12'
  main: 'dist/index.js'
outputs:
  branch-name:
    description: 'The name of branch created'